"""
Provider-independent answer generation from
Phase 11 RetrievalEvidence.

This module performs no retrieval, indexing,
reranking, parent lookup, or citation building.

It consumes the output of the Phase 11 retrieval
service and routes only message generation through
the existing generation gateway.
"""

from __future__ import annotations

import time

from typing import (
    Callable,
    Dict,
    List,
    Optional,
)

from src.core.config import config

from src.generation.evidence_prompt import (
    build_evidence_grounded_messages,
)

from src.generation.generation_gateway import (
    generate,
)

from src.schema.generation_service_models import (
    GenerationRequest,
    GenerationResponse,
)


class EvidenceGenerationError(RuntimeError):
    """Raised when generation violates the contract."""


GeneratorFn = Callable[
    [List[Dict[str, str]]],
    str,
]


def generate_from_evidence(
    request: GenerationRequest,
    *,
    _generator: Optional[GeneratorFn] = None,
    _clock: Callable[[], float] = (
        time.perf_counter
    ),
) -> GenerationResponse:
    """
    Generate a grounded answer from a Phase 11
    evidence contract.

    The provider sees only the prompt assembled
    from request.query and request.evidence.

    Citations are never generated by the model.
    Existing deterministic citation payloads from
    Phase 11 are preserved in the response.
    """

    resolved_model = (
        request.model
        or config.generation_model
    )

    messages = (
        build_evidence_grounded_messages(
            request.query,
            request.evidence,
        )
    )

    started = _clock()

    if _generator is not None:
        raw_answer = _generator(
            messages
        )
    else:
        raw_answer = generate(
            messages,
            model=resolved_model,
        )

    finished = _clock()

    if not isinstance(
        raw_answer,
        str,
    ):
        raise EvidenceGenerationError(
            "Generation backend returned a "
            "non-string response."
        )

    answer_text = raw_answer.strip()

    if not answer_text:
        raise EvidenceGenerationError(
            "Generation backend returned an "
            "empty response."
        )

    sources = [
        item.citation_payload
        for item in request.evidence
    ]

    return GenerationResponse(
        query=request.query,
        answer_text=answer_text,
        model_used=resolved_model,
        generation_backend=(
            config.generation_backend
        ),
        sources=sources,
        evidence=list(
            request.evidence
        ),
        latency_ms=max(
            0.0,
            (
                finished
                - started
            )
            * 1000.0,
        ),
    )
